spring:
  mail: 
    host: smtp.gmail.com
    port: 587
    username: dileandrog@gmail.com
    password: 123456
    properties:
        mail:
            smtp:              
                auth: true
                starttls:
                    enable: true
  datasource: 
    url: jdbc:mysql://localhost:3306/weblab?allowPublicKeyRetrieval=true&useSSL=false&useTimezone=true&serverTimezone=GMT&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver 
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect      
  thymeleaf:
    cache: false 
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      
server:
  error:
    whitelabel:
      enabled: false
  servlet:
    session:
      cookie:
        http-only: true
      tracking-modes:
      - cookie

weblab:
  carpeta:
    fotos: web-files